OPTARG is set to ? when invalid
just print help for help

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -24,7 +24,7 @@ while getopts "ndh" opt; do
 		BACKUP_DELETE=1
 		;;
 	\?)
-		echo "Invalid option: $OPTARG" >&2
+    echo "Invalid option provided. Run $0 -h for help" >&2
 		exit 1
 		;;
 	*)
